### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by manishapb** [manishapb/ping-pong#1]
- [x] Bug: game doesn't stop on page reload
- [x] Set a countdown of 5 secs after player 2 joins game
- [ ] Only allow to start a game if MAX active games
- [x]  Remove rounding from Paddle component 
- [x] Joining should be disabled when 2 players already in a game
- [x] Game updates should only be allowed for players
- [x] Move game info to another component & below the board
